FROM node:18 AS build

WORKDIR /app
COPY frontend/ ./frontend/

WORKDIR /app/frontend
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
